In [1]:
from ultralytics import YOLO

In [9]:
import cv2
import os
import numpy as np
from PIL import Image

def sharpen_image(image_path):
    image = cv2.imread(image_path)
    kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
    sharpened_image = cv2.filter2D(image, -1, kernel)

    return sharpened_image

data_dir="D:/Datasets/pothole_dataset/Pothole main dataset/train/images"
for filename in os.listdir(data_dir):
    # Read the image
    img = PIL.Image.open(os.path.join(data_dir, filename))
    # Apply the transformations to the image
    augmented_img = sharpen_image(img)

    # Save the augmented image
    augmented_img.save(os.path.join(data_dir, "sharpen_" + filename))

NameError: name 'PIL' is not defined

In [ ]:
#Resizer code

import os
from PIL import Image

# Get the path to the folder containing the images
image_folder = "D:/Datasets/pothole_dataset/Pothole main dataset/train/images"

# Get the width and height of the resized images
width = 640
height = 640

# Iterate over the images in the folder
for image in os.listdir(image_folder):

    # Open the image
    img = Image.open(os.path.join(image_folder, image))

    # Resize the image
    img = img.resize((width, height))

    # Save the resized image
    img.save(os.path.join(image_folder, image))


In [9]:
#Image augmentation code

import torchvision.transforms as transforms

# Set the directory of the images to be augmented
data_dir = image_folder

# Define the transformations to be applied
transform = transforms.Compose(
    [
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.2),
    ]
)
# Iterate over the images in the directory
for filename in os.listdir(data_dir):
    # Read the image
    img = PIL.Image.open(os.path.join(data_dir, filename))

    # Apply the transformations to the image
    augmented_img = transform(img)

    # Save the augmented image
    augmented_img.save(os.path.join(data_dir, "augmented_" + filename))


In [2]:
model=YOLO("yolov8n.pt")
model.train(data="D:\Datasets\pothole_dataset\Pothole detection latest\data.yaml", epochs=100)

New https://pypi.org/project/ultralytics/8.0.136 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.100  Python-3.9.16 torch-2.0.1+cpu CPU
yolo\engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=D:\Datasets\pothole_dataset\Pothole detection latest\data.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False,

In [59]:
model=YOLO("D:\Datasets\pothole_dataset/runs\detect/train8\weights/best.pt")
# model.val(data="D:\Datasets\pothole_dataset\Pothole detection latest\data.yaml", show_labels=False, hide_conf=True,augment=False)
model.predict(source="D:\drone_video.webm", save=True, save_txt=True)



    WARNING  stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
    causing potential out-of-memory errors for large sources or long-running streams/videos.

    Usage:
        results = model(source=..., stream=True)  # generator of Results objects
        for r in results:
            boxes = r.boxes  # Boxes object for bbox outputs
            masks = r.masks  # Masks object for segment masks outputs
            probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/369) D:\drone_video.webm: 384x640 3 potholes, 90.5ms
video 1/1 (2/369) D:\drone_video.webm: 384x640 3 potholes, 122.3ms
video 1/1 (3/369) D:\drone_video.webm: 384x640 3 potholes, 88.4ms
video 1/1 (4/369) D:\drone_video.webm: 384x640 3 potholes, 77.1ms
video 1/1 (5/369) D:\drone_video.webm: 384x640 3 potholes, 84.0ms
video 1/1 (6/369) D:\drone_video.webm: 384x640 3 potholes, 77.5ms
video 1/1 (7/369) D:\drone_video.webm: 384x640 3 potholes, 66.5m

[ultralytics.yolo.engine.results.Results object with attributes:
 
 boxes: ultralytics.yolo.engine.results.Boxes object
 keypoints: None
 keys: ['boxes']
 masks: None
 names: {0: 'pothole'}
 orig_img: array([[[ 33,  92,  73],
         [ 31,  90,  71],
         [ 27,  86,  67],
         ...,
         [ 28,  48,  43],
         [ 24,  44,  39],
         [ 43,  63,  58]],
 
        [[ 32,  91,  72],
         [ 27,  86,  67],
         [ 21,  80,  61],
         ...,
         [ 45,  65,  60],
         [ 48,  68,  63],
         [ 61,  81,  76]],
 
        [[ 38,  84,  70],
         [ 36,  82,  68],
         [ 32,  78,  64],
         ...,
         [ 19,  68,  51],
         [  9,  58,  41],
         [ 23,  72,  55]],
 
        ...,
 
        [[ 31, 200, 173],
         [ 47, 216, 189],
         [ 30, 161, 135],
         ...,
         [ 99, 114, 112],
         [ 99, 114, 112],
         [ 99, 114, 112]],
 
        [[ 59, 186, 172],
         [ 80, 207, 193],
         [121, 200, 188],
         ...,
 

In [60]:
model = YOLO('D:\Datasets\pothole_dataset/runs\detect/train8\weights/best.pt')
image_path="D:\pothole.webp"
results=model(image_path)


image 1/1 D:\pothole.webp: 384x640 16 potholes, 72.6ms
Speed: 3.0ms preprocess, 72.6ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)


In [61]:
import cv2
img=cv2.imread(image_path)
for result in results:
    boxes = result.boxes.cpu().numpy() # get boxes on cpu in numpy
    for box in boxes: # iterate boxes
        c=box.cls
        name=model.names[int(c)]
        conf=(str)(round(box.conf[0],2))
        name=name+" "+conf
        print((name))
        r = box.xyxy[0].astype(int) # get corner points as int
        print(r) # print boxes
        cv2.rectangle(img, r[:2], r[2:], (0,255,0), 2) # draw boxes on img
        cv2.putText(
        img,
        name,
        (int(r[0]), int(r[1]) - 10),
        fontFace = cv2.FONT_HERSHEY_SIMPLEX,
        fontScale = 0.3,
        color = (0, 255,255),
        thickness=1
    )
        cv2.imwrite("output2.jpg", img)

pothole 0.92
[436 280 511 308]
pothole 0.87
[666 432 913 668]
pothole 0.87
[563 393 664 428]
pothole 0.86
[565 259 654 287]
pothole 0.85
[692 253 825 303]
pothole 0.83
[477 338 573 380]
pothole 0.83
[678 343 811 409]
pothole 0.79
[193 436 287 496]
pothole 0.79
[410 460 537 558]
pothole 0.77
[303 341 394 389]
pothole 0.76
[1002  421 1179  513]
pothole 0.62
[ 938  207 1200  317]
pothole 0.6
[500 309 599 339]
pothole 0.58
[ 28 546 273 673]
pothole 0.56
[400 243 475 266]
pothole 0.53
[337 294 395 328]


: 